default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  port: 3306

development:
  <<: *default
  database: "calories_tracker"
  username: "root"
  password: ""
  host: "localhost"

test:
  <<: *default
  database: "calories_tracker_test"
  username: "root"
  password: <%= ENV["DB_USER_PASSWORD"] or '' %>
  host: <%= ENV["DB_PRIMARY_PORT_3306_TCP_ADDR"] or "localhost" %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  pool: 16
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV["DB_USER_PASSWORD"] %>
  host: <%= ENV['DB_HOST_MASTER'] %>
