source 'https://rubygems.org'

ruby '2.6.5'
gem 'rails', '~> 6.0.4', '>= 6.0.4.1'
gem 'mysql2', '>= 0.4.4'
gem 'puma', '~> 4.1'
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'rack-cors'
gem 'jwt'
gem 'faker'
gem 'jsonapi.rb'

group :development, :test do
  gem 'factory_bot_rails'
end

group :development do
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'rails-controller-testing'
end
